SET SQL DIALECT 3;

/* CREATE DATABASE 'C:\Users\julio\Documents\Workspace\Estoque\dados\ESTOQUE.GDB' PAGE_SIZE 4096

 DEFAULT CHARACTER SET  */

/* Table: BAIRRO, Owner: SYSDBA */

CREATE TABLE "BAIRRO" 
(
  "BAIRRO_CODIGO"	INTEGER NOT NULL,
  "BAIRRO_NOME"	VARCHAR(30) NOT NULL,
CONSTRAINT "BAIRRO_PK" PRIMARY KEY ("BAIRRO_CODIGO")
);

/* Table: FUNCIONARIO, Owner: SYSDBA */

CREATE TABLE "FUNCIONARIO" 
(
  "FUNC_CODIGO"	INTEGER NOT NULL,
  "FUNC_NOME"	VARCHAR(40) NOT NULL,
  "FUNC_BAIRRO"	VARCHAR(20),
  "FUNC_CIDADE"	INTEGER NOT NULL,
  "FUNC_CARGO"	VARCHAR(20),
  "FUNC_ENDERECO"	VARCHAR(70) NOT NULL,
  "FUNC_CPF"	VARCHAR(14),
  "FUNC_RG"	VARCHAR(20),
  "FUNC_FONERES"	VARCHAR(16),
  "FUNC_DATAADM"	TIMESTAMP,
  "FUNC_DATANASC"	TIMESTAMP,
CONSTRAINT "FUNCIONARIO_PK" PRIMARY KEY ("FUNC_CODIGO")
);

/* Table: LOGRADOURO, Owner: SYSDBA */

CREATE TABLE "LOGRADOURO" 
(
  "LOG_CODIGO"	INTEGER NOT NULL,
  "LOG_LOGRADOURO"	VARCHAR(40) NOT NULL,
CONSTRAINT "LOGRADOURO_PK" PRIMARY KEY ("LOG_CODIGO")
);

/* Table: TBL_CIDADE, Owner: SYSDBA */

CREATE TABLE "TBL_CIDADE" 
(
  "CID_CODIGO"	INTEGER NOT NULL,
  "CID_NOME"	VARCHAR(30) NOT NULL,
  "CID_UF"	VARCHAR(12) NOT NULL,
CONSTRAINT "CIDADE_ID_PK" PRIMARY KEY ("CID_CODIGO")
);

/*  Index definitions for all user tables */

CREATE INDEX "IDX_BAIRRO_COD" ON "BAIRRO"("BAIRRO_CODIGO");
CREATE INDEX "IDX_BAIRRO_NOM" ON "BAIRRO"("BAIRRO_NOME");
CREATE INDEX "IDX_COD_CIDADE" ON "TBL_CIDADE"("CID_CODIGO");
CREATE INDEX "IDX_NOM_CIDADE" ON "TBL_CIDADE"("CID_NOME");

CREATE GENERATOR "GEN_COD_CIDADE";
SET TERM ^ ;


/* Triggers only will work for SQL triggers */

CREATE TRIGGER "GERA_CODIGO_CIDADE" FOR "TBL_CIDADE" 
ACTIVE BEFORE INSERT POSITION 0
as begin
  new.cid_codigo = gen_id(gen_cod_cidade,1);
end
 ^

COMMIT WORK ^
SET TERM ;^

/* Grant Roles for this database */


/* Grant permissions for this database */

